### ISSUE TITLE
Posting Data into IOTA Lambda without API Gateway 30 Sec Timeout

### ISSUE THREAD

**Issue by crypto5000** [vessels-tech/iota-lambda#2]
Hey Lewis! Thanks for putting this package together with the tutorial. I'm starting a new IOTA project (https://github.com/crypto5000/dariota) and wanted to get your advice on best practices for integrating Lamda for PoW. What's the best way to post client side transaction data into Lamda (e.g. a message)? Normally, I'd just integrate with the API Gateway, but it seems there could be timeout issues. So now I'm looking at splitting the logic into 2 Lamda functions that chain and using the invoke method to trigger the other PoW lamda function. Do you have thoughts?

Some brief background on my new project: 
Currently, the IOTA specification doesn't include geolocation. I'm building a project that will enable IOTA transactions to be mapped to locations using GPS. So you'll be able to read/write data to a specific location. Think of it as an augmented reality data layer in the Tangle.

I'm thinking of 2 stages. The first stage seems straightforward. It's just mapping the data to a location. If you have a smartphone or GPS, you can pin your data by location. And you can see the data that exists around you. For this, I'm investigating IOTA Lamda to do the proof of work - because most smartphones won't be able to write to the Tangle.

The second stage is way more complicated and probably too speculative - given it requires adoption of the first stage. It's an incentive system to get people to post data and/or store data. In other words, if you post something helpful (e.g. a review of a business), someone could pay you in IOTA. This would probably require some sort of IOTA splitting (per your other medium article) where some portion would go for long-term storage to prevent snapshot deletion.

Any comments would be appreciated. Thanks again.

**Comment by lewisdaly** [comment]
Hey! Thanks for reaching out. Your project sounds interesting - keep me posted on how it goes. I think it could have some powerful implications for supply chain management. 

I also wonder if there might be a good way to integrate the tangle with IPFS or similar to solve this long-term storage problem. I haven't thought too much on it, but I'll let you know if anything comes to mind.



My thoughts about using the Lambda API Gateway:

When I originally implemented the PoW lambda, I did try to use API Gateway, but the 30 timeout was a major problem. From my understanding, it's a problem for a whole bunch of other people as well, but since the 30 second timeout is tied to other Cloudfront infrastructure (internally within AWS), it's not going to change anytime soon.

>What's the best way to post client side transaction data into Lamda (e.g. a message?)
I'm not 100% sure what you mean by this. Do you mean as an API request?

As you said above, one way you could improve this is by chaining to lambda functions together, which would also require some state management - maybe with DynamoDB since you are in the AWS ecosystem.

You have 2 ApiGateway endpoints, and 1 DynamoDB event handler
- `submitTransaction()`
- `dynamoDBSaveHandler()`
- `checkTransactionStatus()`

`submitTransaction()` does the following:
1. Creates a new transaction
2. Saves the details to dynamoDB
3. Returns to the user, with some id identifying the tx in the database

`dynamoDBSaveHandler()` is a lambda function triggered by a DynamoDB save event, which is the actual lambda that does the PoW, and talks to the tangle. This lambda has a max timeout of 5 minutes.
- once the bundle is signed, submitted to the tangle etc, it updates the status of the tx in dynamoDB

`checkTransactionStatus()`
- user calls this with the previous transaction id, to check on the status of the transaction


From the client side, submitting a transaction would look like the following: (in pseudocode)
```
iotaLambdaApi.submitTransaction();
transactionStatus = pending;
while (transactionStatus == pending) {
  transactionStatus = checkTransactionStatus();
  sleep(30);
}

//handle failed or successful transaction status
```

Let me know if that does or doesn't make sense!

**Comment by crypto5000** [comment]
Awesome. Thanks so much for the advice and help. I'll keep you posted on the project - I tend to launch them on reddit (I've done a bunch already).

1) I was thinking about using a datastore with IOTA Lambda, which is why I reached out. I'm going to investigate this and see performance/cost. It does make sense. 

Do you have thoughts on the following approach that doesn't require state management inside AWS? What if I include a unique tag clientside on the post to the API Gateway for the transaction. This API Gateway is integrated to a simple Lambda that is chained to the PoW Lambda. This first Lambda should execute quickly and get around the 30 second timeout. The first Lambda forwards the posted data to the second Lambda via invoke. The second Lambda then submits the transaction to the Tangle. And, the missing piece is that the clientside process does a 30 second polling to the Tangle to search for the tagged transaction. The client would error to the user if the transaction wasn't found within 2 minutes (4 polls). 

2) I've thought about IPFS for storage. It's the ideal. For the second stage, I've thought about payments, voting, and storage. So you can either store the data permanently yourself (possibly via IPFS), upvote the data (which is used to filter results), or pay someone (either to store it permanently or as a tip for content creation). I'm not going to worry about this until the first stage is built - because it's a big complicated project.

Anyway, thanks again for answering and keep an eye out for the launch. All the best.

**Comment by lewisdaly** [comment]
Yeah my main thought was to use DynamoDB as you can trigger lambdas from DynamoDB events. It might make it easier to handle errors with the transactions, but I don't see why simply triggering one lambda from another and using a unique tag to monitor the transaction wouldn't work.

Re: #2, yeah that sounds like an interesting idea! 

Best of luck!
